name: Run Tests with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: testing-job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.26

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun run test


# https://bun.sh/guides/runtime/cicd